### ISSUE TITLE
Building array from class-string

### ISSUE THREAD

**Issue by a-ayala** [DaveLiddament/php-generics-standard#6]
Hoping someone is able to explain to me why the example below isn't type hinting as I'd expect.

```
class Dog {
    public function talk()
    {
        echo "Woof!";
    }
}

/**
 * @template T
 * @param class-string<T> $className
 * @return array<T>
 */
function buildArray(mixed $className): mixed {
    return [
        new $className,
        new $className,
        new $className,
    ];
}

$dogs = buildArray(Dog::class);
foreach ($dogs as $dog) {
    $dog->talk(); // <-- No type hint?
}
```

Here I'd expect (I'd like) PHPStorm to recognise I'm return an array of `Dog`. Similar to the example of passing an fql works:

```
/**
 * @template T
 * @param class-string<T> $className
 * @return T
 */
function build(string $className) {
    return new $className;
}

$person = build(Person::class); // $person is an object of type Person
```

I'm might be missing something, or should perhaps approach this a different way. Any insight would be appreciated :)

**Comment by orklah** [comment]
Your syntax is valid and understood by both Psalm and PHPStan, the issue must be that PHPStorm has still only partial support for this. `@return array<T>` seem unsupported. I suggest you open an issue in their ticketing tool: https://youtrack.jetbrains.com/issues/WI

**Comment by a-ayala** [comment]
@orklah thanks for the clarification - I'll raise it with Jetbrains
